### PR TITLE
fix file extension issue and improve UI

### PR DESCRIPTION
**Pull request by khatastroffik**
# fix file extension issue

### description
the procedure identifying markdown files is using their extension and fails when the extension contains any uppercase char
* test.md -> ok
* test.MD -> not ok

### solution
identify markdown files regardless of the case of their extension

## UI/Design

- add border to menu (bottom) and footer (top) in light and dark design mode
- enlarge document margin
- fix body top margin (set to 0 when info element is not shown)
- reduce size i.e. height of the footer to better match the height of the menu
 
---
**note**
the links to the issues (issue numbers) in the comments of the commit should point to the issue list on the forked project... though github is not able to "merge" those link (transpose them to point to the originating issue item/project), hence they are now wrongly pointing to this repo. sorry.

### CODE REVIEW

**Comment by c3er** [comment]
Thank you very much for your contribution! The design changes look very good!

I have only two minor issues with the current state of your PR (one very minor):

1. (Very minor): `npm test` does not pass because the `index.html` file has some formatting issues. Can you run `npm run format` and update this PR accordingly?
2. You added a tag "v2.0.1" that interferes with my release process. Can you please remove this tag? A tag "vX.Y.Z" does always correspond with a release with the same version number, i.e. the release is built from the exact commit were the tag is.

> the links to the issues (issue numbers) in the comments of the commit should point to the issue list on the forked project... though github is not able to "merge" those link (transpose them to point to the originating issue item/project), hence they are now wrongly pointing to this repo. sorry.

You may file issues in my repository instead. From the [CONTRIBUTING file](https://github.com/c3er/mdview/blob/master/CONTRIBUTING.md):

> If you like to add some feature or fix an apparent bug, it is recommended to open an issue explaining the change first. This makes it possible to discuss the feature or bug fix first and makes sure that you don't put to much work in the case that the author does not want that particular change to his tool.

**Comment by khatastroffik** [comment]
> Thank you very much for your contribution! The design changes look very good!
> 
you're welcome ;-)

> I have only two minor issues with the current state of your PR (one very minor):
> 
> 1. (Very minor): `npm test` does not pass because the `index.html` file has some formatting issues. Can you run `npm run format` and update this PR accordingly?
> 
> 2. You added a tag "v2.0.1" that interferes with my release process. Can you please remove this tag? A tag "vX.Y.Z" does always correspond with a release with the same version number, i.e. the release is built from the exact commit were the tag is.
> 

I'll do that... though... see below ...

> 
> You may file issues in my repository instead. From the [CONTRIBUTING file](https://github.com/c3er/mdview/blob/master/CONTRIBUTING.md):
> 
I could do so... though I'm used to first develop and commit in the fork, using i.e. linking to issues in the fork repo itself.
Why? IMHO, any repo needs to comply with an Application Lifecycle Management (of work done within it).
The ALM I do follow is usually including: SemVer2, Commit-Message-Guidelines (very much like [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) , GitFlow (using many branches ;-) ) etc.
Sadly, the issues are not shared/merged between forks :-( and I would not be able to track the fork work using issues from another repo... "Teufelskreis" würde ich sagen. This would not be a problem i.e. would not happen when working on the same repo ;-)

> If you like to add some feature or fix an apparent bug, it is recommended to open an issue explaining the change first. This makes it possible to discuss the feature or bug fix first and makes sure that you don't put to much work in the case that the author does not want that particular change to his tool.

this is a pretty "standard way", foremost on gh,  but it totally ignores ALM on the fork. Hence it's "almost ok" but not very "good" when using forked repos... only when there's only some "local dev clones" having only one "origin" to send PR to. It's not working nicelly within a "gh-fork" context.

**Comment by khatastroffik** [comment]
* Tags remved from the fork
* Sources formated
* all tests passing
note: I've removed the version labels from my forked repo, though it doesn't remove the corresponding commit and I can't figure out how to easily exclude these commits. As said... a typical Teufelskreis when PR from a fork to another repo...

**Comment by c3er** [comment]
> IMHO, any repo needs to comply with an Application Lifecycle Management (of work done within it).
The ALM I do follow is usually including: SemVer2, Commit-Message-Guidelines (very much like Conventional Commits , GitFlow (using many branches ;-) ) etc.

IMO this is a little too much for that hobby project. 😂

Now, there is another problem: You already added another feature to this PR (change of code highlighting). You clearly should open another PR for this feature. I have multiple problems with current the state of this feature:

- I don't like the new default for the light theme -- `vs.css` looks much better IMO.
- A change of this theme is not remembered after restart of the tool.
- Some minor issues with code style that is not automatically enforced yet

## Remembering user settings:

 I propose to extend the `Settings`class in `app/lib/main/storage.js`. In the future, the `Settings`class may be renamed `ApplicationSettings`while the current `Encodings` class may be extended to a `DocumentSettings` class, where besides of the document's encoding could be the last window position for that document stored.

## Code style

Looking at this function:

```js
function loadStyle(styleName) {
    // always unload any existing user choosen styling first
    unloadStyle()
    // check if the user has choosen a style (otherwise, it's a "reset" and we're done)
    if (isNull(styleName)) {
        return
    }
    // load user choosen styling i.e. insert a link to css file, since this will override the default styles
    var head = _document.getElementsByTagName("head")[0]
    var path = "../app/css/" + styleName + ".css"
    var link = _document.createElement("link")
    link.href = path
    link.type = "text/css"
    link.rel = "stylesheet"
    link.media = "screen"
    link.id = stylePrefix + styleName
    // save the ID of the loaded style: to be used when unloading...
    _currentStyleId = link.id
    head.appendChild(link)
}
```

This would be better IMO:

```js
function loadStyle(styleName) {
    // Always unload any existing user choosen styling first
    unloadStyle()

    // Check if the user has choosen a style (otherwise, it's a "reset" and we're done)
    if (lodash.isNull(styleName)) {
        return
    }

    // Load user choosen styling i.e. insert a link to css file, since this will override the default styles
    const head = _document.getElementsByTagName("head")[0]
    const path = "../app/css/" + styleName + ".css"
    const link = _document.createElement("link")
    link.href = path
    link.type = "text/css"
    link.rel = "stylesheet"
    link.media = "screen"
    link.id = stylePrefix + styleName

    // Save the ID of the loaded style: to be used when unloading...
    _currentStyleId = link.id

    head.appendChild(link)
}
```

Before a comment line should be an empty line. And after the code fragment that belongs to that comment should be also a blank. This way, it is better visible, what the comment tries to explain.

`var` has another semantic as in virtually all other languages with C syntax while `let` has that semantic and may be less confusing for people that work not only with JavaScript. And as long as the value does not change after initialization, `const` should always be preferred.

---

I prefer

```js
const lodash = require("lodash")
```

over

```js
const { isNull } = require("lodash")
```

In the calling code it is better visible that `isNull` is part of the `lodash` library

---

```js
"../app/css/" + styleName + ".css"
```

Why don't you use string interpolation?

```js
`../app/css/"${styleName}.css`
```

**Comment by khatastroffik** [comment]
> 
> 
> > IMHO, any repo needs to comply with an Application Lifecycle Management (of work done within it).
> > The ALM I do follow is usually including: SemVer2, Commit-Message-Guidelines (very much like Conventional Commits , GitFlow (using many branches ;-) ) etc.
> 
> IMO this is a little too much for that hobby project. 😂

I do feel with you 😁 though I'm so used to it, that I'm faster following it than without... 

> 
> Now, there is another problem: You already added another feature to this PR (change of code highlighting). You clearly should open another PR for this feature. I have multiple problems with current the state of this feature:
> 
>     * I don't like the new default for the light theme -- `vs.css` looks much better IMO.
> 
>     * A change of this theme is not remembered after restart of the tool.

"*incremental feature development*" (aka "lean"+"agile", somehow 😉): that could be the next step/feature.
 
> 
>     * Some minor issues with code style that is not automatically enforced yet
> 
> 
> ## Remembering user settings:
> 
> I propose to extend the `Settings`class in `app/lib/main/storage.js`. In the future, the `Settings`class may be renamed `ApplicationSettings`while the current `Encodings` class may be extended to a `DocumentSettings` class, where besides of the document's encoding could be the last window position for that document stored.
> ## Code style
> 
> Looking at this function:
> 
> ```js
> function loadStyle(styleName) {
>     // always unload any existing user choosen styling first
>     unloadStyle()
>     // check if the user has choosen a style (otherwise, it's a "reset" and we're done)
>     if (isNull(styleName)) {
>         return
>     }
>     // load user choosen styling i.e. insert a link to css file, since this will override the default styles
>     var head = _document.getElementsByTagName("head")[0]
>     var path = "../app/css/" + styleName + ".css"
>     var link = _document.createElement("link")
>     link.href = path
>     link.type = "text/css"
>     link.rel = "stylesheet"
>     link.media = "screen"
>     link.id = stylePrefix + styleName
>     // save the ID of the loaded style: to be used when unloading...
>     _currentStyleId = link.id
>     head.appendChild(link)
> }
> ```
> 
> This would be better IMO:
> 
> ```js
> function loadStyle(styleName) {
>     // Always unload any existing user choosen styling first
>     unloadStyle()
> 
>     // Check if the user has choosen a style (otherwise, it's a "reset" and we're done)
>     if (lodash.isNull(styleName)) {
>         return
>     }
> 
>     // Load user choosen styling i.e. insert a link to css file, since this will override the default styles
>     const head = _document.getElementsByTagName("head")[0]
>     const path = "../app/css/" + styleName + ".css"
>     const link = _document.createElement("link")
>     link.href = path
>     link.type = "text/css"
>     link.rel = "stylesheet"
>     link.media = "screen"
>     link.id = stylePrefix + styleName
> 
>     // Save the ID of the loaded style: to be used when unloading...
>     _currentStyleId = link.id
> 
>     head.appendChild(link)
> }
> ```
> 
> Before a comment line should be an empty line. And after the code fragment that belongs to that comment should be also a blank. This way, it is better visible, what the comment tries to explain.
> 
> `var` has another semantic as in virtually all other languages with C syntax while `let` has that semantic and may be less confusing for people that work not only with JavaScript. And as long as the value does not change after initialization, `const` should always be preferred.
> 
> I prefer
> 
> ```js
> const lodash = require("lodash")
> ```
> 
> over
> 
> ```js
> const { isNull } = require("lodash")
> ```

tradeoff between "CommonJS style" vs "ES6 style" vs "YAGNI" (targeted import-> reduced footprint/dependencies...).

Actually, this should better be coded as `import { isNull } from "lodash"` (see also the very similar TypeScript and Python "import statement" styles)  but I used "require" here to not break with the already used CJS style too much. 

> In the calling code it is better visible that `isNull` is part of the `lodash` library
> 
> ```js
> "../app/css/" + styleName + ".css"
> ```
> 
> Why don't you use string interpolation?
> 
> ```js
> `../app/css/"${styleName}.css`
> ```

I usually do ;-) missed that one...

**Comment by c3er** [comment]
> "incremental feature development" (aka "lean"+"agile", somehow 😉): that could be the next step/feature.

An extra PR for this would be better🙂

**Comment by khatastroffik** [comment]
I'm closing this PR since there's too much issue in maintaining the connection between the two repos at the moment:

when I'm creating a PR to the master branch on my forked repo, it will **automatically forward/add the PR to this repo** as well (at least as long as the PR is not commited here). Actually, I could solve this by not doing PR on my "master" at all, though leaving my code in a "development" stage/branch. In other words, my development efforts are either "totally separated" or "totally dependent" of your repository... or... I'm to foolish to find a way arround...

**Comment by khatastroffik** [comment]
The lag of branches (e.g. "development") in your repo does limit the options for external contributions, since one cannot create PRs but directly to the master branch, which in turn is bound to your release process which in turn ... etc.

**Comment by c3er** [comment]
> The lag of branches (e.g. "development") in your repo does limit the options for external contributions, since one cannot create PRs but directly to the master branch, which in turn is bound to your release process which in turn ... etc.

Just make a feature branch for each feature that you want to implement, so you can make a dedicated PR for each. They can be discussed, improved and merged separately. That's the usual way in GitHub and I don't see much problem, if it's done this way.

**Comment by khatastroffik** [comment]
as explained...

## PR from a checked out, local (repo on dev PC) "feature" branche does not work
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream ORIG develop:master
```
> remote: Permission to c3er/mdview.git denied to khatastroffik.
> fatal: unable to access 'https://github.com/c3er/mdview.git/': The requested URL returned error: 403
> Pushing to https://github.com/c3er/mdview.git
> Completed with errors, see above.

## PR from a forked github

this will work but only permit to PR into the master branch (which is not suitable with your release policy) and with drawbacks (e.g. the "automatic" mentioned above).

**Comment by khatastroffik** [comment]
> ... That's the usual way in GitHub and I don't see much problem, if it's done this way.

just my 2 cents 😉 :

`usual != good` and `(this.usual in global.goodPractices)? true : false` would return `false`.
* why should I take it as it is? or
* why should I try to find a workarround to the "usual" impediments at repeatedly 3x the cost of the original effort?

BTW:

> “Why` do you necessarily have to be wrong just because a few million people think you are?”
> ― *Frank Zappa*

and 
> “Without deviation from the norm, progress is not possible.”
> ― *Frank Zappa*
and 

> "One of my favorite philosophical tenets is that people will agree with you only if they already agree with you. You do not change people's minds."
> ― *Frank Zappa*


>“The white zone is for loading and unloading only.
> If you gotta load or unload, go to the white zone...”
> ― *Frank Zappa*

Though, at the end...

> There’s no reason to assume that my idea of what‘s better would really be better. I resent it when other people try to inflict their ideas of betterness on me. 
> ― *Frank Zappa*

😄

**Comment by c3er** [comment]
I see, you develop your fork now on your own. Is it OK, if I still integrate the changes of this PR in my version? Also, I'd like to use some features that you developed already as inspiration for my version (direct integration is now virtually impossible, after you reformatted the source files).

Sorry for the late response. I had almost no time last week.

**Comment by khatastroffik** [comment]
Hey Christian,
sure! feel free!
I had to start refactoring the code a bit ;-) since some bugs needed to be fixed and I wanted to get a better insight of how things happen in the app... btw: I've just started dev with Electron, so I had to take the refactoring task ... precautiously 😋

**Comment by c3er** [comment]
OK, thanks!

**Pull request closed without merging**
